#ifndef PLUGINMANAGERLIBRARY_H
#define PLUGINMANAGERLIBRARY_H

#include <QtCore/QtGlobal>

#if defined(PLUGINMANAGER_LIBRARY)
#  define PLUGINMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINMANAGERLIBRARY_H
