#ifndef CONNECTIONMANAGERLIBRARY_H
#define CONNECTIONMANAGERLIBRARY_H

#include <QtCore/QtGlobal>

#if defined(CONNECTIONMANAGER_LIBRARY)
#  define CONNECTIONMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define CONNECTIONMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // CONNECTIONMANAGERLIBRARY_H

