#ifndef PLUGINS_OPENSPEEDSHOP_CONNECTIONMANAGERLIBRARY_H
#define PLUGINS_OPENSPEEDSHOP_CONNECTIONMANAGERLIBRARY_H

#include <Global.h>

#if defined(CONNECTIONMANAGER_LIBRARY)
#  define CONNECTIONMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define CONNECTIONMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINS_OPENSPEEDSHOP_CONNECTIONMANAGERLIBRARY_H

