#ifndef PLUGINS_OPENSPEEDSHOP_OPENSPEEDSHOPLIBRARY_H
#define PLUGINS_OPENSPEEDSHOP_OPENSPEEDSHOPLIBRARY_H

#include <Global.h>

#if defined(OPENSPEEDSHOP_LIBRARY)
#  define OPENSPEEDSHOP_EXPORT Q_DECL_EXPORT
#else
#  define OPENSPEEDSHOP_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINS_OPENSPEEDSHOP_OPENSPEEDSHOPLIBRARY_H
