#ifndef SETTINGMANAGERLIBRARY_H
#define SETTINGMANAGERLIBRARY_H

#include <QtCore/QtGlobal>

#if defined(SETTINGMANAGER_LIBRARY)
#  define SETTINGMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGMANAGERLIBRARY_H
